[package]
name = "perkeep-types"
version = "0.1.0"
authors = ["Ian Denhardt <ian@zenhack.net>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
